{{ define "header" }}
# Code generated by dagger. DO NOT EDIT.

from __future__ import annotations

import warnings  # noqa: F401
from collections.abc import Callable
from dataclasses import dataclass
from datetime import date, datetime, time
from decimal import Decimal

from typing_extensions import Self

from dagger.client._core import Arg
from dagger.client._guards import typecheck
from dagger.client.base import Enum, Input, Root, Scalar, Type
{{ end }}
