query ModuleConfig($source: ModuleSourceID!) {
    source: loadModuleSourceFromID(id: $source) {
        kind
        digest
        asString
        sdk {
            source
        }
        sourceRootSubpath
        commit
        version
        htmlRepoURL
        module: asModule {
            name
            description
            dependencies {
                name
                description
                source {
                    id
                    asString
                    digest
                }
            }
        }
    }
}
